from dataclasses import dataclass

@dataclass
class DataIngestionArtifact:
    feature_store_file_path:str
    train_file_path:str
    test_file_path:str

class DataValidationArifact:...
class DataTransformationArifact:...
class ModelTrainerArifact:...
class ModelEvaluationArifact:...
class ModelPusherArifact:...